config/routes.rb
Rails.application.routes.draw do
  get 'summaries/index'
  get 'wrappers/index'
  get 'wrappers/show'
  get 'events/index'
  get 'events/show'
  get 'events/new'
  get 'events/edit'
  get 'events/create'

  # devise_for :users
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root "memos#index"
  resources :users, only: [:new, :edit, :update]
  resources :memos, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :events, only:[:index, :show, :new, :create, :edit, :update, :destroy]
  resources :summaries, only:[:index]
  resources :folders,  only:[:index, :show, :new, :create, :edit, :update, :destroy]
  resources :tags,  only:[:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
  end
  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :events
    end
  end
end

app/models/memo.rb
class Memo < ApplicationRecord

  has_many :tag_memos
  has_many :tags, through: :tag_memos, dependent: :destroy
  belongs_to :user
  # belongs_to :event
  has_one :event

  mount_uploader :image, ImageUploader

  def self.filter(selected_tag_ids) # Tag id array checked with form.
    selected_memo_ids = TagMemo.where(tag_id: selected_tag_ids).pluck(:memo_id).uniq.sort # Memo id array associated to checked tag.
    return Memo.all unless selected_tag_ids 
    memo_filtered = [] # Memo id array associated to all tags checked with form.
    selected_memo_ids.each do |id|
      loop_count = 0
      while selected_tag_ids.length > loop_count do
        break unless Memo.includes(:tags).find(id).tags.pluck(:id).include?(selected_tag_ids[loop_count].to_i)
        loop_count += 1; # Get memo id that associated tag id is equall to all tag id selected.
      end
      memo_filtered << id if loop_count == selected_tag_ids.length
    end
    return memo_filtered
  end
end

app/views/shared/_contents_center.html.haml
.wrapper__contents__center__memo__info
  .wrapper__contents__center__memo__info__title
    = simple_format(@memo.title)
  .wrapper__contents__center__memo__info__date
    = simple_format(@memo.updated_at.strftime("%Y年%m月%d日 %H時%M分"))
.wrapper__contents__center__memo__content
  .wrapper__contents__center__memo__content__text
    = simple_format(@memo.text) if @memo.text.present?
  = image_tag @memo.image.url, class: 'image', size: '300x300' if @memo.image.present?
.wrapper__contents__center__memo__bottom
  .wrapper__contents__center__memo__bottom__tags
    - @tags.each do |tag|
      %i.fas.fa-tags
      .wrapper__contents__center__memo__bottom__tags__name
        = simple_format(tag.name) if tag.present?
  .wrapper__contents__center__memo__bottom__icon
    .wrapper__contents__center__memo__bottom__icon__edit
      = link_to edit_memo_path(@memo) do
        = icon('fas',' fa-edit')
    .wrapper__contents__center__memo__bottom__icon__delete
      = link_to icon('fas',' fa-trash-alt'), memo_path(@memo), method: :delete

app/views/shared/_contents_index.html.haml
.wrapper__contents__index__head
  .wrapper__contents__index__head__sub_title
    = "Memo list"
%ul.wrapper__contents__index__ul
  - @memos.each do |memo|
    = link_to memo_path(memo) do
      %li.wrapper__contents__index__ul__list
        .wrapper__contents__index__ul__list__title
          = memo.title
        .wrapper__contents__index__ul__list__content
          .wrapper__contents__index__ul__list__content__text
            = memo.text
          = image_tag memo.image.url, class: '.wrapper__contents__index__ul__list__content__image', size: '30x30' if memo.image.present?
        .wrapper__contents__index__ul__list__date
          = memo.updated_at.strftime("%Y/%m/%d")
.wrapper__contents__index__pagination
  = paginate @memos

app/views/shared/_contents_left.html.haml
.wrapper__contents__left
  %ul.wrapper__contents__left__ul
    - @memos.each do |memo|
      = link_to memo_path(memo) do
        %li.wrapper__contents__left__ul__list
          .wrapper__contents__left__ul__list__title
            = memo.title
          .wrapper__contents__left__ul__list__content
            .wrapper__contents__left__ul__list__content__text
              = memo.text
            = image_tag memo.image.url, class: 'image', size: '90x90' if memo.image.present?
          .wrapper__contents__left__ul__list__date
            = memo.updated_at.strftime("%Y/%m/%d")

app/views/shared/_contents_right.html.haml
%ul.wrapper__contents__right__ul
  .wrapper__contents__right__ul__title
    = "Tag list"
  = form_with(url: search_tags_path, local: true, method: :get, class: "wrapper__contents__right__ul__search-form") do |form|
    - @user_folders.each do |user_folder|
      .wrapper__contents__right__ul__search-form__folder
        = icon('fas',' fa-folder')
        = user_folder.name
        - user_folder.tags.each do |tag|
          %li.wrapper__contents__right__ul__search-form__folder__list
            = form.check_box :tag_ids, { multiple: true, include_hidden: false, class: "wrapper__contents__right__ul__search-form__folder__list__checkbox" }, tag.id
            -# form.check_box :配列名, { 複数のチェックボックスをひとまとめに扱うか, uncheck時に0の自動取得を回避, class:"クラス名" }, "チェック時に取得する値"
            .wrapper__contents__right__ul__search-form__folder__list__icon
              = icon('fas',' fa-tags')
            = form.label tag.name, class:"wrapper__contents__right__ul__search-form__folder__list__name"
    = form.submit 'Search', class: "wrapper__contents__right__ul__search-form__submit"
  .wrapper__contents__right__ul__bottom
    %br.wrapper__contents__right__ul__bottom__guide
    = "※It will search with And condition"
    = link_to icon('fas',' fa-edit'), folders_path(@user_folder), class: "wrapper__contents__right__ul__bottom__edit", method: :get

app/views/shared/_contents_show.html.haml
.wrapper__contents__center__memo__info
  .wrapper__contents__center__memo__info__title
    = simple_format(@memo.title)
.wrapper__contents__center__memo__content
  .wrapper__contents__center__memo__content__text
    = simple_format(@memo.text) if @memo.text.present?
  = image_tag @memo.image.url, class: 'image', size: '240x240' if @memo.image.present?
.wrapper__contents__center__memo__bottom
  .wrapper__contents__center__memo__bottom__date
    = simple_format(@memo.updated_at.strftime("%Y/%m/%d/ %H:%M"))
  .wrapper__contents__center__memo__bottom__tags
    - @tags.each do |tag|
      %i.fas.fa-tags
      .wrapper__contents__center__memo__bottom__tags__name
        = simple_format(tag.name) if tag.present?
  .wrapper__contents__center__memo__bottom__icon
    .wrapper__contents__center__memo__bottom__icon__edit
      = link_to edit_memo_path(@memo) do
        = icon('fas',' fa-edit')
    .wrapper__contents__center__memo__bottom__icon__delete
      = link_to icon('fas',' fa-trash-alt'), memo_path(@memo), method: :delete

app/views/shared/_folder_index.haml
.wrapper__contents__folder_index
  %ul.wrapper__contents__folder_index__ul
    .wrapper__contents__folder_index__ul__title
      = "Edit tag list"
    .wrapper__contents__folder_index__ul__tree
      - @user_folders.each do |user_folder|
        .wrapper__contents__folder_index__ul__tree__folder
          .wrapper__contents__folder_index__ul__tree__folder__list
            .wrapper__contents__folder_index__ul__tree__folder__list__icon
              = icon('fas',' fa-folder')
            .wrapper__contents__folder_index__ul__tree__folder__list__name
              = user_folder.name
          .wrapper__contents__folder_index__ul__tree__folder__button
            = link_to icon('fas',' fa-edit'), edit_folder_path(user_folder), class: "wrapper__contents__folder_index__ul__tree__folder__button__edit"
            = link_to icon('fas',' fa-trash-alt'), folder_path(user_folder), class: "wrapper__contents__folder_index__ul__tree__folder__button__delete", method: :delete
        - user_folder.tags.each do |tag|
          .wrapper__contents__folder_index__ul__tree__tag
            %li.wrapper__contents__folder_index__ul__tree__tag__list
              .wrapper__contents__folder_index__ul__tree__tag__list__icon
                = icon('fas',' fa-tags')
              = link_to tag.name,edit_tag_path(tag) , class: "wrapper__contents__folder_index__ul__tree__tag__list__name"
            .wrapper__contents__folder_index__ul__tree__tag__button
              = link_to icon('fas',' fa-edit'),edit_tag_path(tag) , class: "wrapper__contents__folder_index__ul__tree__tag__edit"
              = link_to icon('fas',' fa-trash-alt'), tag_path(tag),class: "wrapper__contents__folder_index__ul__tree__tag__delete", method: :delete

app/views/shared/_form.html.haml
.new_message
  =form_for [@memo] do |f|
    .new_message__input
      .new_message__input__form
        %p
          title
        = f.text_field :title, class: 'new_message__input__form__title',placeholder: 'type a title'
        %p
          content
        = f.text_area :text, class: 'new_message__input__form__text',placeholder: 'type a content'
        .new_message__input__form__mask
          =f.label :image, class: 'new_message__input__form__mask__image' do
            = icon('fas', 'image', class: 'icon')
            = f.file_field :image, class: 'hidden'
      .new_message__input__attributes
        %p.new_message__input__attributes__title
          tag
        .new_message__input__attributes__board
          - @user_folders.each do |user_folder|
            .new_message__input__attributes__board__folder
              .new_message__input__attributes__board__folder__icon
                = icon('fas',' fa-folder')
              .new_message__input__attributes__board__folder__name
                = user_folder.name
            .new_message__input__attributes__board__tag
              = f.collection_check_boxes :tag_ids, user_folder.tags, :id, :name do |b|
                = b.label(class:"new_message__input__attributes__board__tag__cbx") { b.check_box + " " + icon('fas',' fa-tags') + " "  + b.text }
    = f.submit 'Register', class: 'new_message__submit_btn'

app/views/shared/_form_folder.html.haml
.new_folder
  = form_for [@folder] do |f|
    = f.text_field :name, class: 'new_folder__field',placeholder: 'type new folder name'
    = f.submit 'Register', class: 'new_folder__submit_btn'

app/views/shared/_form_tag.html.haml
.new_tag
  = form_for [@tag] do |f|
    = f.text_field :name, class: 'new_tag__field',placeholder: 'type new tag name'
    .new_tag__folder
      .new_tag__folder__guide
        = "Folder to associate"
      .new_tag__folder__selection
        - @user_folders.each do |folder|
          = f.radio_button :folder_id, folder.id
          = f.label folder.name
      = f.submit 'Register', class: 'new_tag__submit_btn'

app/views/shared/_top_bar.haml
= link_to root_path, class: "wrapper__top_bar__title", :method => :get do
  %i.fas.fa-republican
    MemoSpace

.wrapper__top_bar__menu
  %div#wrapper
    %p.btn-gnavi#wrapper
      %span
      %span
      %span

    %nav#global-navi
      %ul.menu
        %li
          = link_to new_memo_path, class: "menu__new_file" do
            .menu__new_file__icon
              %p#new_file.fas.fa-plus-circle
              %i#new_file.far.fa-file-alt
            %p.menu__new_file__guide#guide NewMemo
        %li
          = link_to new_tag_path, class: "menu__new_tag" do
            .menu__new_tag__icon
              %p#new_tag.fas.fa-plus-circle
              %i#new_tag.fas.fa-tags
            %p.menu__new_tag__guide#guide NewTag
        %li
          = link_to new_folder_path, class: "menu__new_folder" do
            .menu__new_folder__icon
              %p#new_folder.fas.fa-plus-circle
              %i#new_folder.far.fa-folder
            %p.menu__new_folder__guide#guide NewFolder
        %li
          .menu__tag_search
            %a.menu__tag_search__title#tag_search_title
              %i#search.fas.fa-search
              %p#search.menu__tag_search__title__guide#guide Search
            %ul.menu__tag_search__ul#tag_search
              = form_with(url: search_tags_path, local: true, method: :get, class: "menu__tag_search__ul__search-form") do |form|
                - @user_folders.each do |user_folder|
                  .menu__tag_search__ul__search-form__folder
                    = icon('fas',' fa-folder')
                    = user_folder.name
                    - user_folder.tags.each do |tag|
                      %li.menu__tag_search__ul__search-form__folder__list
                        = form.check_box :tag_ids, { multiple: true, include_hidden: false, class: "menu__tag_search__ul__search-form__folder__list__checkbox" }, tag.id
                        -# form.check_box :配列名, { 複数のチェックボックスをひとまとめに扱うか, uncheck時に0の自動取得を回避, class:"クラス名" }, "チェック時に取得する値"
                        %i.fas.fa-tags.menu__tag_search__ul__search-form__folder__list__icon
                        = form.label tag.name, class:"menu__tag_search__ul__search-form__folder__list__name"
                = form.submit 'Search', class: "menu__tag_search__ul__search-form__submit"
        %li
          = link_to folders_path(@user_folder), class: "menu__edit_tag_list", method: :get do
            .menu__edit_tag_list__icon#icon
              %i.fas.fa-edit
            %p.menu__edit_tag_list__guide#guide EditTagList
        %li
          =link_to destroy_user_session_path, class: "menu__logout", method: :delete do
            .menu__logout__icon#icon
              %i.fas.fa-.fa-sign-out-alt
            %p.menu__logout__guide#guide Logout
.wrapper__top_bar__user
  %i.far.fa-user
    #{@user.name}